bluelog/models.py
from datetime import datetime

from werkzeug.security import generate_password_hash, check_password_hash

from bluelog.extensions import db

class Admin(db.Model):
    __tablename__ = 'admin'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(20),unique=True)
    password_hash = db.Column(db.String(128))
    blog_title = db.Column(db.String(60))
    blog_sub_title = db.Column(db.String(100))
    name = db.Column(db.String(30))
    about = db.Column(db.Text)
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def validate_password(self, password):
        return check_password_hash(self.password_hash, password)

class Category(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(30),unique=True)
    posts = db.relationship('Post',back_populates='category')

class Post(db.Model):
    id =  db.Column(db.Integer,primary_key=True)
    title =  db.Column(db.String(60))
    body =  db.Column(db.Text)
    timestamp = db.Column(db.DateTime,default=datetime.utcnow)
    category_id = db.Column(db.Integer,db.ForeignKey('category.id'))
    category = db.relationship('Category',back_populates='posts')
    comments = db.relationship('Comment',back_populates='post',cascade='all')

class Comment(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    author = db.Column(db.String(20))
    email = db.Column(db.String(254))
    site = db.Column(db.String(255))
    body =  db.Column(db.Text)
    from_admin =  db.Column(db.Boolean,default=False)
    reviewed = db.Column(db.Boolean,default=False)
    timestamp = db.Column(db.DateTime,default=datetime.utcnow,index=True)
    post_id = db.Column(db.Integer,db.ForeignKey('post.id'))
    post = db.relationship('Post',back_populates='comments')
    replied_id = db.Column(db.Integer,db.ForeignKey('comment.id'))
    replied = db.relationship('Comment',back_populates='replies',remote_side=[id])
    replies = db.relationship('Comment',back_populates='replied',cascade='all')

bluelog/forms.py
from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, HiddenField
from wtforms.validators import DataRequired, Length, ValidationError, Email, Optional, URL

from bluelog import Category


class LoginForm(FlaskForm):
    username = StringField('Username',validators=[DataRequired(),Length(1,20)])
    password = PasswordField('Password',validators=[DataRequired(),Length(1,20)])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired(),Length(1,50)])
    category = StringField('Category', coerce=int,default=1)
    body = CKEditorField('Body',validators=[DataRequired()])
    submit = SubmitField()
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name)
                                 for category in Category.query.order_by(Category.name).all()]
class Category(FlaskForm):
    name = StringField('Name',validators=[DataRequired(),Length(1,20)])
    submit = SubmitField()
    def validate_name(self,field):
        if Category.query.filter_by(name=field.data).first():
            raise ValidationError('Name already in use.')

class CommentForm(FlaskForm):
    author = StringField('Name', validators=[DataRequired(),Length(1,30)])
    email = StringField('Email',validators=[DataRequired(),Email(),Length(1,30)])
    site = StringField('Site',validators=[Optional(),URL(),Length(0,255)])
    body = TextAreaField('Comment',validators=[DataRequired()])
    submit =  SubmitField()

class AdminComment(CommentForm):
    author = HiddenField()
    email = HiddenField()
    site =  HiddenField()

bluelog/__init__.py
from flask import Flask, render_template
import os
import click

from bluelog.blueprints import blog, admin, auth
from bluelog.blueprints.blog import blog_bp
from bluelog.settings import config
from bluelog.blueprints.auth import auth_bp
from bluelog.blueprints.admin import admin_bp
from bluelog.extensions import db, ckeditor, mail

#def make_app(config_name=None):
from models import Admin, Category


def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_ENV','development')
    app = Flask('bluelog')
    app.config.from_object(config[config_name])
    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True
    register_logging(app)
    register_extensions(app)
    register_blueprints(app)
    register_shell_context(app)
    register_template_context(app)
    register_commands(app)
    register_errors(app)
    return app

def register_logging(app):
    pass
def register_extensions(app):
    db.init_app(app)
    mail.init_app(app)
    ckeditor.init_app(app)

def register_blueprints(app):
    app.register_blueprint(blog_bp)
    app.register_blueprint(admin_bp,url_prefix='/admin')
    app.register_blueprint(auth_bp,url_prefix='/auth')

def register_shell_context(app):
    @app.shell_context_processor
    def make_shell_context():
        return dict(db=db)
def register_template_context(app):
    @app.context_processor
    def make_template_context():
        admin = Admin.query.first()
        categories = Category.query.order_by(Category.name).all()
        return dict(admin=admin, categories=categories)
def register_commands(app):
    @app.cli.command()
    @click.option('--category', default = 10, help = 'Quantity of categories, default is 10.')
    @click.option('--post', default=50, help = 'Quantity of posts, default is 50.')
    @click.option('--comment', default=500, help='Quantity of comments, default is 500.')
    def forge(category, post, comment):
        """Generates the fake categories, posts, and comments."""
        from bluelog.fakes import fake_categories,fake_posts,fake_comments, fake_admim
        db.drop_all()
        db.create_all()
        click.echo('Generating the administrator...')
        fake_admim()
        click.echo('Generating %d categories...'% category)
        fake_categories()
        click.echo('Generating %d posts...' % post)
        fake_posts()
        click.echo('Generating %d comments...' % comment)
        fake_comments()
        click.echo('Done.')


def register_errors(app):
    @app.errorhandler(400)
    def bad_request():
        return render_template('errors/400.html'), 400
#app.register_blueprint(auth_bp, url_prefix='/auth') #/auth/login
#app.register_blueprint(auth_bp,subdomain='auth') #auth.example.com/login

bluelog/blueprints/admin.py
from flask import Blueprint

admin_bp = Blueprint('admin',__name__,template_folder='templates')
@admin_bp.route('/index')
def index():
    return 'Hello admin index'

bluelog/blueprints/auth.py
from flask import Blueprint
auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login')
def login():
    return 'Hello login'
@auth_bp.route('/logout')
def logout():
    return 'hello logout'
@auth_bp.route('/index')
def index():
    return 'hello auth index'

bluelog/blueprints/blog.py
from flask import Blueprint, render_template

import bluelog
from bluelog.models import Post

blog_bp = Blueprint('blog', __name__)
@blog_bp.route('/')
def index():
    posts = bluelog.models.Post.query.order_by(bluelog.models.Post.timestamp.desc()).all()
    return render_template('blog/index.html', posts=posts)

@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')

@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    return render_template('blog/category.html')

@blog_bp.route('/post/<int:post_id>', methods=['GET','POST'])
def show_post(post_id):
    return render_template('blog/post.html')

bluelog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width",initial-scal="1,shrink-to-fit=no">
        <title>{% block title %}{% endblock title %} - Bluelog</title>
        <link rel="icon" href="{{ url_for('static',filename='favicon') }}">
        <link rel="stylesheet" href="{{ url_for('static',filename='css/%s.min.css'% request.cookies.get('theme', 'perfect_blue'))}}" type="text/css">
        <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}" type="text/css">
    {% endblock head %}
</head>
<body>
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="/">Bluelog</a>
        <button type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navba-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock nav %}
<main class="container">
    {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
    {% endfor %}
    ...
    {% block content %}{% endblock content %}
    {% block footer %}
        <footer>
        ...
        </footer>
    {% endblock footer %}
</main>
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
{% endblock scripts %}
</body>
</html>

bluelog/templates/blog/_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bluelog/templates/blog/_sidebar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if categories %}
<div class="card mb-3">
    <div class="card-header">Categories</div>
    <ul class="list-group list-group-flush">
        {% for category in categories %}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <a href="{{ url_for('blog.show_category', category_id=category.id) }}">
                {{ category.name }}
            </a>
            <span class="badge badeg-primary badge-pill">{{ category.posts|length }}</span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}


</body>
</html>

bluelog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bluelog/templates/blog/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bluelog/templates/blog/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bluelog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    <div class="page-header">
        <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
        <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
    </div>
    {% if posts %}
        {% for post in posts %}
            <h3 class="text-primary"><a href="{{ url_for('.show_post',post_id=post.id) }}">{{ post.title }}</a></h3>
            <p>
                {{ post.body|striptags|truncate }}
                <small><a href="{{ url_for('.show_post',post_id=post.id) }}">Read More</a></small>
            </p>
            <small>
                Comments:<a href="{{ url_for('.show_post',post_id=post.id) }}#comments">{{ post.comments|length }}</a>
                Category:<a href="{{ url_for('.show_category',category_id=post.category.id) }}">{{ post.category.name }}</a>
                <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
            </small>
            {% if not loop.last %}
                <hr>
            {% endif %}
        {% endfor %}
        {% else %}
            <div class="tip">
                <h5>No posts yet.</h5>
                {% if current_user.is_authenticates %}
                        <a href="{{ url_for('admin.new_post') }}">Write Now</a>
                {% endif %}
            </div>
        {% endif %}

    {% endif %}
{% endblock content %}
</body>
</html>

bluelog/templates/blog/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>